// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGroluGeZrcyIb5_ErUng_QrDRl4CyZJ4',
    appId: '1:837625825071:web:d7a181cddfb3114afd03da',
    messagingSenderId: '837625825071',
    projectId: 'nepflix-b066b',
    authDomain: 'nepflix-b066b.firebaseapp.com',
    storageBucket: 'nepflix-b066b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpubN5OUxyWm4gLFYMas_Z4BWAMS2ZEzs',
    appId: '1:837625825071:android:d9af1a0d5f70ff65fd03da',
    messagingSenderId: '837625825071',
    projectId: 'nepflix-b066b',
    storageBucket: 'nepflix-b066b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObjA9mbmueTR50vxwba4dNaGDvUUiM0k',
    appId: '1:837625825071:ios:6533a3697871e5e4fd03da',
    messagingSenderId: '837625825071',
    projectId: 'nepflix-b066b',
    storageBucket: 'nepflix-b066b.appspot.com',
    iosBundleId: 'com.example.nepflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAObjA9mbmueTR50vxwba4dNaGDvUUiM0k',
    appId: '1:837625825071:ios:7cc451d222c758a1fd03da',
    messagingSenderId: '837625825071',
    projectId: 'nepflix-b066b',
    storageBucket: 'nepflix-b066b.appspot.com',
    iosBundleId: 'com.example.nepflix.RunnerTests',
  );
}
